# Using Postgres local database for development
default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000
  username: ubuntu

development:
  <<: *default
  database: bb_dev
  pool: 5

test:
  <<: *default
  database: bb_test

production:
  <<: *default
  database: bb_prod
